In [ ]:
import pandas as pd
import numpy as np
data=data={"name":["sun","moon","then"],
      "age":["25","24","25"],
      "cholestral":[230,255,266]
      }

df=pd.DataFrame(data)

print(df.isnull())

    name    age  cholestral
0  False  False       False
1  False  False       False
2  False  False       False

In [ ]:
df_cleaned = df.dropna()
print(df_cleaned)

   name age  cholestral
0   sun  25         230
1  moon  24         255
2  then  25         266

In [ ]:
import pandas as pd
import numpy as np
data={"name":["sun","moon","then"],
      "BMI":["25","24","25"],
      "cholestral":[230,255,266]
      }

df=pd.DataFrame(data)
print('before imputation:')
print(df)
df['BMI'].fillna(df['cholestral'].median(),inplace=True)
print("\n after imputation:")
print(df)

before imputation:
   name BMI  cholestral
0   sun  25         230
1  moon  24         255
2  then  25         266

 after imputation:
   name BMI  cholestral
0   sun  25         230
1  moon  24         255
2  then  25         266

<ipython-input-17-7dd1ae9d6ef6>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BMI'].fillna(df['cholestral'].median(),inplace=True)

In [18]:
df.fillna(df.mode().iloc[0],
          inplace=True)
print(df)

   name BMI  cholestral
0   sun  25         230
1  moon  24         255
2  then  25         266

In [19]:
df.fillna(method='ffill').fillna(method='bfill')

<ipython-input-19-96f8eeab00d8>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill').fillna(method='bfill')

   name BMI  cholestral
0   sun  25         230
1  moon  24         255
2  then  25         266

In [29]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
data={"name":["sun","moon","then"],
      "BMI":["25","24","25"],
      "cholestral":[230,255,266]
      }

df=pd.DataFrame(data)

scaler=StandardScaler()
df_scaled=df.copy()
df_scaled[['BMI','cholestral']]= scaler.fit_transform(df[['BMI','cholestral']])
print(df_scaled)

   name       BMI  cholestral
0   sun  0.707107   -1.349901
1  moon -1.414214    0.309813
2  then  0.707107    1.040088

In [35]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data={"name":["sun","moon","then"],
      "BMI":["25","24","25"],
      "cholestral":[230,255,266]
      }
scaler = MinMaxScaler()
df=pd.DataFrame(data)
df_scaled=df.copy()
df_scaled[['BMI','cholestral']]= scaler.fit_transform(df[['BMI','cholestral']])
print(df_scaled)

   name  BMI  cholestral
0   sun  1.0    0.000000
1  moon  0.0    0.694444
2  then  1.0    1.000000

In [37]:
df_encoded=pd.get_dummies(df,columns=['name']),
drop_first=True
print(df_encoded)

(  BMI  cholestral  name_moon  name_sun  name_then
0  25         230      False      True      False
1  24         255       True     False      False
2  25         266      False     False       True,)

In [38]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
df['name'] = encoder.fit_transform(df['name'])
print(df)

   name BMI  cholestral
0     1  25         230
1     0  24         255
2     2  25         266

In [46]:
def performance_category(cholestral):
  if cholestral >=85:
    return "High"
  elif cholestral >=70:

    return "Medium"
  else:
    return"Low"
df["performance"]=df["cholestral"].apply(performance_category)
print(df)

   name BMI  cholestral performance
0     1  25         230        High
1     0  24         255        High
2     2  25         266        High

In [54]:
data={"name":["sun","moon","then"],
      "age":[25,24,25],
      "cholestral":[230,255,266]
      }
df=pd.DataFrame(data)
df["age_group"]= pd.cut(df["age"], bins=[20,30,40],labels=["young","adult"])
print(df)

   name  age  cholestral age_group
0   sun   25         230     young
1  moon   24         255     young
2  then   25         266     young